// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/demo.vue')['default']
    EchartsView: typeof import('./src/components/Echarts/EchartsView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/Echarts/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
